package com.jscms.frame;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

import com.jolbox.bonecp.BoneCP;
import com.jolbox.bonecp.BoneCPConfig;
/*后续这里可以实现连接池这些操作*/
public class JSDbConnection {
	private static JSConnectionPool connectionPool=null;
	private Connection conn;
	private Statement statement;
	private ResultSet result;
	public JSDbConnection(){
		try {
			if(connectionPool==null){
				synchronized (JSDbConnection.class) {
					if(connectionPool==null){
						connectionPool = JSConnectionPoolFactor.getConnectionPool();
					}
				}
			}
			conn = connectionPool.getConnection();
			statement = conn.createStatement();
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		
	}
	
	public ResultSet query(String sql){
		try {
			result = statement.executeQuery(sql);
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}finally{
		}
		return result;
		
	}
	
	public int update(String sql){
		int rows=-1;
		int autoGeneratedKeys=0;
		try {
			
			rows = statement.executeUpdate(sql, autoGeneratedKeys);
			
			if(rows<0){
				//执行失败
			}
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		
		return rows;
		
	}
	
	public void execute(String sql){
		try {
			
			if(!statement.execute(sql)){
				//执行失败
			}
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		
	}
	
	public void closeAll(){
		// 释放结果集连接  
        if (result != null) {  
            try {  
                result.close();  
            } catch (SQLException e) {  
                System.out.println(e.getMessage());  
            }  
        }
        // 释放声明连接  
        if (statement != null) {  
            try {  
                statement.close();  
            } catch (SQLException e) {  
                System.out.println(e.getMessage());  
            }  
        }
        // 释放数据库连接  
        if (conn != null) {  
            try {  
                conn.close();  
            } catch (SQLException e) {  
                System.out.println(e.getMessage());  
            }  
        }  
	}
	public void closeConn(){
		// 释放数据库连接  
        if (conn != null) {  
            try {  
                conn.close();  
            } catch (SQLException e) {  
                System.out.println(e.getMessage());  
            }  
        }  
	}
}
